// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from "@supabase/ssr";
import type { Database } from "./types";

const meta = (import.meta as unknown as { env?: Record<string, string | undefined> }).env ?? {};

const SUPABASE_URL = meta.VITE_SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY =
  meta.VITE_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
