name: Full Stack Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NODE_VERSION: 20.18.1
  PNPM_VERSION: 10.19.0

jobs:
  setup:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    outputs:
      cache-key: ${{ steps.pnpm-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Validate environment configuration
        run: pnpm run check:env
      - name: Restore pnpm store
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install workspace deps
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint & Typecheck
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run typecheck

  test:
    name: Unit & Integration Tests
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test -- --coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
        if: always()

  security:
    name: Security & Compliance
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Dependency audit (prod only)
        run: pnpm audit --prod --json
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
        continue-on-error: false
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci

  build-web:
    name: Build PWAs
    needs: security
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Build client PWA
        run: pnpm --filter @ibimina/client run build
      - name: Build admin PWA
        run: pnpm --filter @ibimina/admin run build
      - name: Archive Next outputs
        uses: actions/upload-artifact@v4
        with:
          name: pwa-build-artifacts
          path: |
            apps/pwa/client/.next
            apps/pwa/staff-admin/.next
        if: always()

  lighthouse:
    name: Lighthouse CI
    needs: build-web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install --frozen-lockfile
      - name: Start preview server
        run: pnpm --filter @ibimina/client run start &
      - name: Run Lighthouse
        run: npx @lhci/cli autorun --config=apps/pwa/client/lighthouse.config.cjs
      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-client
          path: .lighthouseci
        if: always()

  build-mobile:
    name: Build Mobile Artifacts
    needs: security
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install --frozen-lockfile
      - name: Build Android AAB
        run: pnpm --filter @ibimina/mobile run build:android:release
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: Build QA APK
        run: pnpm --filter @ibimina/mobile run build:android:apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: Build iOS IPA
        run: pnpm --filter @ibimina/mobile run build:ios:release
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: Upload mobile artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-builds
          path: apps/mobile/dist
        if: always()

  deploy:
    name: Promote to Environments
    needs:
      - lighthouse
      - build-mobile
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://client.ibimina.rw
    steps:
      - name: Await manual approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: "release-managers"
          timeout-minutes: 120
      - name: Deploy to Vercel
        run: pnpm --filter @ibimina/client run deploy:vercel:fallback
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PROD_TOKEN }}
      - name: Trigger Supabase migrations
        run: pnpm --filter @ibimina/admin run supabase:deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  staging-smoke:
    name: Staging Smoke (auth + invite)
    needs: deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install workspace deps
        run: pnpm install --frozen-lockfile
      - name: Run staging smoke test
        run: pnpm --filter @ibimina/staff-admin-pwa run test:e2e -- --project=chromium --config=playwright.config.ts
        env:
          PLAYWRIGHT_REMOTE: 1
          PLAYWRIGHT_REMOTE_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
          PLAYWRIGHT_REMOTE_EMAIL: ${{ secrets.STAGING_ADMIN_EMAIL }}
          PLAYWRIGHT_REMOTE_PASSWORD: ${{ secrets.STAGING_ADMIN_PASSWORD }}
          PLAYWRIGHT_INVITE_EMAIL: ${{ secrets.STAGING_INVITE_EMAIL }}
          PLAYWRIGHT_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          PLAYWRIGHT_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
          PLAYWRIGHT_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }}
