-- Add missing columns to saccos table
ALTER TABLE public.saccos 
ADD COLUMN IF NOT EXISTS province text,
ADD COLUMN IF NOT EXISTS email text,
ADD COLUMN IF NOT EXISTS category text DEFAULT 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)';
-- Insert all SACCO data
INSERT INTO public.saccos (name, sector_code, district, province, email, category, status) VALUES
('UMWALIMU SACCO', 'KIMIRONKO', 'GASABO', 'CITY OF KIGALI', 'umwalimu.sacco@umwalimusacco.rw', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC UBAKA', 'KIMIRONKO', 'GASABO', 'CITY OF KIGALI', 'coopecubaka@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC ZAMUKA', 'GATENGA', 'KICUKIRO', 'CITY OF KIGALI', 'coopeczamuka2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('CYCLE INVESTMENT COOPERATIVE (CIC SACCO)', 'GISOZI', 'GASABO', 'CITY OF KIGALI', 'cycleinvestmentcooperative@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC IKIRENGA', 'BASE', 'RULINDO', 'NORTHERN PROVINCE', 'coopecikirenga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MTG ISHEMA SACCO', 'KANIGA', 'GICUMBI', 'NORTHERN PROVINCE', 'mtgishemasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('PFUNDA TEA FARMERS AND WORKERS SACCO (PTFW SACCO)', 'NYUNDO', 'RUBAVU', 'WESTERN PROVINCE', 'ptfwsacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COMICOKA', 'KANAMA', 'RUBAVU', 'WESTERN PROVINCE', 'comicokacoopec2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TEA SHAGASHA', 'GIHEKE', 'RUSIZI', 'WESTERN PROVINCE', 'saccoteas@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPERATIVE OF PROGRESS AND FINANCING (CPF) INEZA', 'NYAMABUYE', 'MUHANGA', 'SOUTHERN PROVINCE', 'cpfineza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC IMPAMBA', 'GIKONKO', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccoimpamba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('CT NYAMAGABE', 'GASAKA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'ctnyamagabe63@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC TWIZIGAMIRE', 'GASAKA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'coopectwizigamire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GATARE TEA FARMERS SACCO', 'KARAMBI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'gatareteafarmerssacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOJAD BUGESERA', 'NYAMATA', 'BUGESERA', 'EASTERN PROVINCE', 'coojadbugeserac@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC INGASHYA', 'KARENGE', 'RWAMAGANA', 'EASTERN PROVINCE', 'coopingashya09@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('AMIZERO SACCO GISAKURA', 'BUSHEKERI', 'NYAMASHEKE', 'WESTERN PROVINCE', 'amizero2011@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MUGANGA SACCO', 'KICUKIRO', 'KICUKIRO', 'CITY OF KIGALI', 'info@mugangasacco.rw', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IKAPAGI', 'BUMBOGO', 'GASABO', 'CITY OF KIGALI', 'koperativeikapagi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('HOPE SACCO MUHIMA', 'MUHIMA', 'NYARUGENGE', 'CITY OF KIGALI', 'muhimahopesacco@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIGALI SACCO', 'KIGALI', 'NYARUGENGE', 'CITY OF KIGALI', 'kigali10sacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('EJOHEZA SACCO', 'NYARUGENGE', 'NYARUGENGE', 'CITY OF KIGALI', 'kehn2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ICYIZERE SACCO GITEGA', 'GITEGA', 'NYARUGENGE', 'CITY OF KIGALI', 'icyizeresacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO MAGERAGERE ICYEREKEZO', 'MAGERAGERE', 'NYARUGENGE', 'CITY OF KIGALI', 'saccomageragere@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDATWA SACCO KANYINYA', 'KANYINYA', 'NYARUGENGE', 'CITY OF KIGALI', 'indatwasaccokanyinya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KUNGAHARA SACCO NYAKABANDA', 'NYAKABANDA', 'NYARUGENGE', 'CITY OF KIGALI', 'kungaharasacconyakabanda7@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('URUGWIRO SACCO', 'RWEZAMENYO', 'NYARUGENGE', 'CITY OF KIGALI', 'urugwirosaccorwezamenyo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('DEVELOPMENT VISION SACCO', 'KIMISAGARA', 'NYARUGENGE', 'CITY OF KIGALI', 'kimisagarasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TRUST SACCO NYAMIRAMBO', 'NYAMIRAMBO', 'NYARUGENGE', 'CITY OF KIGALI', 'trustsacco2020@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GATSATA SACCO AMIZERO', 'GATSATA', 'GASABO', 'CITY OF KIGALI', 'amizerogatsata@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GIKOMERO SACCO(KOPEKUKUGI)', 'GIKOMERO', 'GASABO', 'CITY OF KIGALI', 'gikomerosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GISOZI SACCO', 'GISOZI', 'GASABO', 'CITY OF KIGALI', 'gisozisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ICYEREKEZO KINYINYA', 'KINYINYA', 'GASABO', 'CITY OF KIGALI', 'sacco2014sik@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IJABO REMERA SACCO', 'REMERA', 'GASABO', 'CITY OF KIGALI', 'ijaboremera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDATSIKIRA SACCO KIMIHURURA', 'KIMIHURURA', 'GASABO', 'CITY OF KIGALI', 'indatsikirasaccokimihurura@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('JABANA SACCO', 'JABANA', 'GASABO', 'CITY OF KIGALI', 'jabanasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUNARA SACCO JALI', 'JALI', 'GASABO', 'CITY OF KIGALI', 'umunarasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KACYIRU SACCO', 'KACYIRU', 'GASABO', 'CITY OF KIGALI', 'kacyiru.sacco2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('HOME BASKET SACCO KIMIRONKO', 'KIMIRONKO', 'GASABO', 'CITY OF KIGALI', 'hobasketsacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE ZIGAMA GURINZWA NDUBA', 'NDUBA', 'GASABO', 'CITY OF KIGALI', 'kozigundusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RUSORORO SACCO', 'RUSORORO', 'GASABO', 'CITY OF KIGALI', 'rusororosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO RUTUNGA', 'RUTUNGA', 'GASABO', 'CITY OF KIGALI', 'saccorutunga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ZAMUKA BUMBOGO SACCO', 'BUMBOGO', 'GASABO', 'CITY OF KIGALI', 'zamukabumbogosacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NDERA SACCO', 'NDERA', 'GASABO', 'CITY OF KIGALI', 'saccondera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KANOMBE SACCO', 'KANOMBE', 'KICUKIRO', 'CITY OF KIGALI', 'kanombesaccoo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBONEZA SACCO', 'NYARUGUNGA', 'KICUKIRO', 'CITY OF KIGALI', 'imbonezasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ABAHIZI SACCO', 'GIKONDO', 'KICUKIRO', 'CITY OF KIGALI', 'saccogikondo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IJABO SACCO KIGARAMA', 'KIGARAMA', 'KICUKIRO', 'CITY OF KIGALI', 'ijabosaccokigaramaa@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IJABO SACCO KICUKIRO', 'KICUKIRO', 'KICUKIRO', 'CITY OF KIGALI', 'ijabo.sacco@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('VISION SACCO GAHANGA (VISAGA)', 'GAHANGA', 'KICUKIRO', 'CITY OF KIGALI', 'saccogahanga@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ICYEREKEZO MASAKA SACCO', 'MASAKA', 'KICUKIRO', 'CITY OF KIGALI', 'icyerekezomasakasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GATENGA SACCO', 'GATENGA', 'KICUKIRO', 'CITY OF KIGALI', 'gatengasacco18@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KAGARAMA SAVINGS AND CREDIT COOPERATIVE', 'KAGARAMA', 'KICUKIRO', 'CITY OF KIGALI', 'kagasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDAHIGWA SACCO NIBOYE', 'NIBOYE', 'KICUKIRO', 'CITY OF KIGALI', 'niboyesacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TWIYUBAKE GASHORA SACCO', 'GASHORA', 'BUGESERA', 'EASTERN PROVINCE', 'twiyubakegashorasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ZAMUKA JURU SACCO', 'JURU', 'BUGESERA', 'EASTERN PROVINCE', 'zamukaj@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KAMABUYE SACCO', 'KAMABUYE', 'BUGESERA', 'EASTERN PROVINCE', 'kamabuyesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('JYAMBERE MAREBA SACCO', 'MAREBA', 'BUGESERA', 'EASTERN PROVINCE', 'jambescom@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MAYANGE SACCO', 'MAYANGE', 'BUGESERA', 'EASTERN PROVINCE', 'saccomaya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBARUTSO MUSENYI SACCO', 'MUSENYI', 'BUGESERA', 'EASTERN PROVINCE', 'musenyisacco2009@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MWOGO SACCO', 'MWOGO', 'BUGESERA', 'EASTERN PROVINCE', 'mwogosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IJABO NGERUKA SACCO', 'NGERUKA', 'BUGESERA', 'EASTERN PROVINCE', 'ijabongerukasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NTARAMA SACCO', 'NTARAMA', 'BUGESERA', 'EASTERN PROVINCE', 'saccontarama@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NYAMATA SACCO', 'NYAMATA', 'BUGESERA', 'EASTERN PROVINCE', 'nyamatasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NYARUGENGE ICYEREKEZO SACCO', 'NYARUGENGE', 'BUGESERA', 'EASTERN PROVINCE', 'nyarugengesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RILIMA SACCO', 'RILIMA', 'BUGESERA', 'EASTERN PROVINCE', 'saccorilima1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RUHUHA DEVELOPMENT SACCO', 'RUHUHA', 'BUGESERA', 'EASTERN PROVINCE', 'ruhuhadevelop2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RWERU SACCO', 'RWERU', 'BUGESERA', 'EASTERN PROVINCE', 'rwerusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SHYARA SACCO', 'SHYARA', 'BUGESERA', 'EASTERN PROVINCE', 'saccoshyaranews@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBONI KIGABIRO SACCO', 'KIGABIRO', 'RWAMAGANA', 'EASTERN PROVINCE', 'imbonikigabiro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBADUKO MUHAZI SACCO', 'MUHAZI', 'RWAMAGANA', 'EASTERN PROVINCE', 'imbaduko2010@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ICYEREKEZO GISHARI SACCO', 'GISHARI', 'RWAMAGANA', 'EASTERN PROVINCE', 'saccogishari@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MUNYIGINYA SACCO (MY SACCO)', 'MUNYIGINYA', 'RWAMAGANA', 'EASTERN PROVINCE', 'smunyiginya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMPORE MWULIRE SACCO', 'MWULIRE', 'RWAMAGANA', 'EASTERN PROVINCE', 'saccomwulire2014@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUSARE SACCO-MUSHA', 'MUSHA', 'RWAMAGANA', 'EASTERN PROVINCE', 'umusaresacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SANGWA SACCO GAHENGERI', 'GAHENGERI', 'RWAMAGANA', 'EASTERN PROVINCE', 'sangwasaccogahengeri1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('FUMBWE SACCO', 'FUMBWE', 'RWAMAGANA', 'EASTERN PROVINCE', 'fumbwesacco20@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUGISHA SACCO MUYUMBU', 'MUYUMBU', 'RWAMAGANA', 'EASTERN PROVINCE', 'umugisha.sacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC UBUMWE BWA NYAKARIRO', 'NYAKARIRO', 'RWAMAGANA', 'EASTERN PROVINCE', 'ubumwebwanyakaliro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GWIZA KARENGE SACCO', 'KARENGE', 'RWAMAGANA', 'EASTERN PROVINCE', 'gwizakarenges@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IZIGAMIRE NZIGE SACCO', 'NZIGE', 'RWAMAGANA', 'EASTERN PROVINCE', 'kpnzigesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IZERE RUBONA SACCO', 'RUBONA', 'RWAMAGANA', 'EASTERN PROVINCE', 'rubonasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TWIYUBAKE MUNYAGA SACCO', 'MUNYAGA', 'RWAMAGANA', 'EASTERN PROVINCE', 'twiyubakesaccomunyaga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GAHINI SACCO', 'GAHINI', 'KAYONZA', 'EASTERN PROVINCE', 'gahinisacco2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE KUNGAHARA KABARE', 'KABARE', 'KAYONZA', 'EASTERN PROVINCE', 'coopeckuka2009@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO DUKIRE KABARONDO', 'KABARONDO', 'KAYONZA', 'EASTERN PROVINCE', 'kabarondosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ICYOGERE MUKARANGE', 'MUKARANGE', 'KAYONZA', 'EASTERN PROVINCE', 'saccomukarange@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('DUKIRE SACCO MURAMA', 'MURAMA', 'KAYONZA', 'EASTERN PROVINCE', 'saccodukiremurama2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCOMURUNDI', 'MURUNDI', 'KAYONZA', 'EASTERN PROVINCE', 'saccomurundi2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MWILI SACCO', 'MWIRI', 'KAYONZA', 'EASTERN PROVINCE', 'saccomwili@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO DUKIRE NDEGO', 'NDEGO', 'KAYONZA', 'EASTERN PROVINCE', 'saccoyacu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC ABANZUMUGAYO/NYAMIRAMA', 'NYAMIRAMA', 'KAYONZA', 'EASTERN PROVINCE', 'sacconyamirama.rw@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO UMUCYO RUKARA', 'RUKARA', 'KAYONZA', 'EASTERN PROVINCE', 'saccoumucyo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO RURAMIRA ICYEREKEZO', 'RURAMIRA', 'KAYONZA', 'EASTERN PROVINCE', 'ruramirasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TWIFATANYE RWINKWAVU', 'RWINKWAVU', 'KAYONZA', 'EASTERN PROVINCE', 'twifatanyesacco@gmil.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE ABIZERANYE Y''I GASHANDA(KOPABIGA)', 'GASHANDA', 'NGOMA', 'EASTERN PROVINCE', 'saccogashanda@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('AMEREKEZO JARAMA SACCO (KOPAJA)', 'JARAMA', 'NGOMA', 'EASTERN PROVINCE', 'sacco2009jarama@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPERATIVE IMENA ZA KAREMBO(CIMEKA)', 'KAREMBO', 'NGOMA', 'EASTERN PROVINCE', 'saccokarembocimeka@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KAZO SAVING AND CREDIT COOPERATIVE', 'KAZO', 'NGOMA', 'EASTERN PROVINCE', 'saccokazo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE ZIGAMA KIBUNGO (KOZIKI)', 'KIBUNGO', 'NGOMA', 'EASTERN PROVINCE', 'kozikingo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IBYIZA MUGESERA SACCO', 'MUGESERA', 'NGOMA', 'EASTERN PROVINCE', 'saccomugesera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOTIMU', 'MURAMA', 'NGOMA', 'EASTERN PROVINCE', 'saccomurama@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INGOBOKA MUTENDERI', 'MUTENDERI', 'NGOMA', 'EASTERN PROVINCE', 'ingobokamutenderisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('REMERA PEOPLE SAVING AND CREDIT COOPERATIVE', 'REMERA', 'NGOMA', 'EASTERN PROVINCE', 'repsaccoremera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KUNGAHARA RUKIRA SACCO', 'RUKIRA', 'NGOMA', 'EASTERN PROVINCE', 'saccorukira20@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ZIGAMA INTERA RUKUMBELI', 'RUKUMBERI', 'NGOMA', 'EASTERN PROVINCE', 'koziru@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RURENGE PEOPLE SACCO (RP SACCO)', 'RURENGE', 'NGOMA', 'EASTERN PROVINCE', 'saccorurenge13@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE ZIGAMA ISANGE MURI SAKE(KOZISA)', 'SAKE', 'NGOMA', 'EASTERN PROVINCE', 'saccosake@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO NTUSIGARE(KOZINTU)', 'ZAZA', 'NGOMA', 'EASTERN PROVINCE', 'saccozaza20@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('JYAMBERE GAHARA', 'GAHARA', 'KIREHE', 'EASTERN PROVINCE', 'saccojyamberegahara@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('VISION SACCO GATORE', 'GATORE', 'KIREHE', 'EASTERN PROVINCE', 'visionsaccogatore1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMIRASIRE Y''ITERAMBERE SACCO KIGARAMA', 'KIGARAMA', 'KIREHE', 'EASTERN PROVINCE', 'saccokigarama@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIGINA SACCO', 'KIGINA', 'KIREHE', 'EASTERN PROVINCE', 'casacoki@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO RUGERO', 'KIREHE', 'KIREHE', 'EASTERN PROVINCE', 'saccorugero@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IMBERE HEZA MAHAMA', 'MAHAMA', 'KIREHE', 'EASTERN PROVINCE', 'saccoimbereheza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO HAGURUKA UKORE-MPANGA', 'MPANGA', 'KIREHE', 'EASTERN PROVINCE', 'saccompanga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURUNGA SACCO MUSAZA', 'MUSAZA', 'KIREHE', 'EASTERN PROVINCE', 'umurungasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MUSHIKIRI SACCO DEVELOPMENT(M.S.D)', 'MUSHIKIRI', 'KIREHE', 'EASTERN PROVINCE', 'mushikirisacoo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO MENYIBANGA', 'NASHO', 'KIREHE', 'EASTERN PROVINCE', 'saccomenyibanganasho@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TWUNGURANE SACCO', 'NYAMUGARI', 'KIREHE', 'EASTERN PROVINCE', 'twunguranesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NYARUBUYE SACCO VISION', 'NYARUBYE', 'KIREHE', 'EASTERN PROVINCE', 'nyarubuyesaccovision@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBARUTSO SACCO GATUNDA', 'GATUNDA', 'NYAGATARE', 'EASTERN PROVINCE', 'imbarutsosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC ISANGE KARAMA', 'KARAMA', 'NYAGATARE', 'EASTERN PROVINCE', 'umurenge12@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KARANGAZI UMURENGE SACCO', 'KARANGAZI', 'NYAGATARE', 'EASTERN PROVINCE', 'karangazisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KATABAGEMU SACCO (CESEKA)', 'KATABAGEMU', 'NYAGATARE', 'EASTERN PROVINCE', 'katabagemusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UBUSUGIRE SACCO KIYOMBE', 'KIYOMBE', 'NYAGATARE', 'EASTERN PROVINCE', 'ubusugiresaccokiyombe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MATIMBA VISION SACCO', 'MATIMBA', 'NYAGATARE', 'EASTERN PROVINCE', 'mavisacco2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURABYO SACCO MIMURI', 'MIMURI', 'NYAGATARE', 'EASTERN PROVINCE', 'saccoumurabyo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INGOBOKA MUKAMA', 'MUKAMA', 'NYAGATARE', 'EASTERN PROVINCE', 'saccoingobokamukama@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MUSHELI SACCO', 'MUSHERI', 'NYAGATARE', 'EASTERN PROVINCE', 'musacco07@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NYAGATARE DEVELOPMENT SACCO', 'NYAGATARE', 'NYAGATARE', 'EASTERN PROVINCE', 'nyagataresacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KARIBU SACCO RUKOMO', 'RUKOMO', 'NYAGATARE', 'EASTERN PROVINCE', 'karibusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RWEMPASHA SACCO', 'RWEMPASHA', 'NYAGATARE', 'EASTERN PROVINCE', 'saccorwempasha@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TURWANYUBUKENE RWIMIYAGA', 'RWIMIYAGA', 'NYAGATARE', 'EASTERN PROVINCE', 'saccorwimiyaga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TABAGWE', 'TABAGWE', 'NYAGATARE', 'EASTERN PROVINCE', 'umurenge10scco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TURWUBAKANE GASANGE "COTUGA SACCO"', 'GASANGE', 'GATSIBO', 'EASTERN PROVINCE', 'cotugasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GATSIBO UMURAGE SACCO', 'GATSIBO', 'GATSIBO', 'EASTERN PROVINCE', 'umuragewubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GITOKI IZERE SACCO', 'GITOKI', 'GATSIBO', 'EASTERN PROVINCE', 'gitokiizeresacco01@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ISONGA SACCO KABARORE', 'KABARORE', 'GATSIBO', 'EASTERN PROVINCE', 'kabaroreisongasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KAGEYO SACCO IZIGAME', 'KAGEYO', 'GATSIBO', 'EASTERN PROVINCE', 'kageyosaccoizigame@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIRAMURUZI UKURI SACCO', 'KIRAMURUZI', 'GATSIBO', 'EASTERN PROVINCE', 'ukurisaccokiramuruzi10@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIZIGURO ISONGA SACCO', 'KIZIGURO', 'GATSIBO', 'EASTERN PROVINCE', 'kizigurosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUHIGO SACCO MUHURA', 'MUHURA', 'GATSIBO', 'EASTERN PROVINCE', 'umuhigosacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INGENZI MURAMBI SACCO', 'MURAMBI', 'GATSIBO', 'EASTERN PROVINCE', 'musaccingenzi2009@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NGARAMA ISUNGE SACCO', 'NGARAMA', 'GATSIBO', 'EASTERN PROVINCE', 'ngaramasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TERIMBERE NYAGIHANGA (SACCOTENYA)', 'NYAGIHANGA', 'GATSIBO', 'EASTERN PROVINCE', 'saccotenya@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('REMERA SACCO GIRIBAKWE', 'REMERA', 'GATSIBO', 'EASTERN PROVINCE', 'saccogiribakwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RUGARAMA URUMURI SACCO', 'RUGARAMA', 'GATSIBO', 'EASTERN PROVINCE', 'rugaramaurumurisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUGANEHEZA SACCO RWIMBOGO', 'RWIMBOGO', 'GATSIBO', 'EASTERN PROVINCE', 'tuganehezasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IREMBO RY''UBUKIRE KAYENZI', 'KAYENZI', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccokayenzi@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IBONEMO GACURABWENGE (SIGA)', 'GACURABWENGE', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccogacurabwege@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IMARABUKENE NGAMBA', 'NGAMBA', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccongamba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO URUYANGERUKOMA (SUR)', 'RUKOMA', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccorukoma@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INYUMBA YA KAYUMBU', 'KAYUMBU', 'KAMONYI', 'SOUTHERN PROVINCE', 'ssaccoinyumba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO MBONEZISONGA MUSAMBIRA', 'MUSAMBIRA', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccombonezisonga@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO URUFUNGUZO RW''UBUKIRE RUNDA', 'RUNDA', 'KAMONYI', 'SOUTHERN PROVINCE', 'ubukirerundasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ICYUZUZO RUGALIKA', 'RUGALIKA', 'KAMONYI', 'SOUTHERN PROVINCE', 'rugalikasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KIRA KARAMA', 'KARAMA', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccokarama@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ISHEMA RY''UMURYANGO NYAMIYAGA (SISUNYA)', 'NYAMIYAGA', 'KAMONYI', 'SOUTHERN PROVINCE', 'sisunyasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO DUSIZE UBUKENE NYARUBAKA', 'NYARUBAKA', 'KAMONYI', 'SOUTHERN PROVINCE', 'nyarubakasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO MUGINA JYAMBERE (SAMUJYA)', 'MUGINA', 'KAMONYI', 'SOUTHERN PROVINCE', 'saccomugina@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ICYEREKEZO SACCO', 'MUSHISHIRO', 'MUHANGA', 'SOUTHERN PROVINCE', 'mushishiro1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IMBANGUKIRAGUKIRA', 'KIBANGU', 'MUHANGA', 'SOUTHERN PROVINCE', 'imbangukiragukirasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TERIMBERE SHYOGWE', 'SHYOGWE', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccoshyogwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO AMIZERO RONGI', 'RONGI', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccoumurengerongi18@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KORA UTEGANYA', 'NYAMABUYE', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccokoruteganya2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUGANE SACCO NYABINONI', 'NYABINONI', 'MUHANGA', 'SOUTHERN PROVINCE', 'tuganesacconyabinoni@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO DUKIRE NYARUSANGE', 'NYARUSANGE', 'MUHANGA', 'SOUTHERN PROVINCE', 'nyarusangesacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ICYEREKEZO KIYUMBA', 'KIYUMBA', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccokiyumba2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IZIGAMIRE KABACUZI', 'KABACUZI', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccoizigamire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO WISIGARA MUHANGA', 'MUHANGA', 'MUHANGA', 'SOUTHERN PROVINCE', 'msaccowisigara@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO AMIZERO RUGENDABARI', 'RUGENDABARI', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccamirug2009@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INGERI CYEZA', 'CYEZA', 'MUHANGA', 'SOUTHERN PROVINCE', 'saccoingericyeza@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('JYAMBERE BWERAMANA', 'BWERAMANA', 'RUHANGO', 'SOUTHERN PROVINCE', 'saccobweramana2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INGENZI SACCO BYIMANA', 'BYIMANA', 'RUHANGO', 'SOUTHERN PROVINCE', 'sbyimana@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC KABAGALI', 'KABAGALI', 'RUHANGO', 'SOUTHERN PROVINCE', 'saccokabagali@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('', 'KINAZI', 'RUHANGO', 'SOUTHERN PROVINCE', 'saccokinazi2017@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC URUBUTO KINIHIRA', 'KINIHIRA', 'RUHANGO', 'SOUTHERN PROVINCE', 'coopecurubutokinihira@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBONEZACYEREKEZO SACCO', 'MBUYE', 'RUHANGO', 'SOUTHERN PROVINCE', 'saccombuye@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ABAHIZI DUKIRE MWENDO', 'MWENDO', 'RUHANGO', 'SOUTHERN PROVINCE', 'sacco.abahizidukire@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NKUNGANIRE', 'NTONGWE', 'RUHANGO', 'SOUTHERN PROVINCE', 'sacconkunganirentongwe2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO BATUREBEREHO RUHANGO', 'RUHANGO', 'RUHANGO', 'SOUTHERN PROVINCE', 'saccobaturebereho2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TEGANYA BUSASAMANA', 'BUSASAMANA', 'NYANZA', 'SOUTHERN PROVINCE', 'busasamanasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO VISION BUSORO', 'BUSORO', 'NYANZA', 'SOUTHERN PROVINCE', 'savibu@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO JYEJURU CYABAKAMYI', 'CYABAKAMYI', 'NYANZA', 'SOUTHERN PROVINCE', 'saccojyejurucyabakamyi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('EJO HEZA TUZAMURANA SACCO KIBIRIZI', 'KIBIRIZI', 'NYANZA', 'SOUTHERN PROVINCE', 'saccokibirizi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO UMURAVA KIGOMA', 'KIGOMA', 'NYANZA', 'SOUTHERN PROVINCE', 'saccokigoma@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TUZAMURANE MUKINGO', 'MUKINGO', 'NYANZA', 'SOUTHERN PROVINCE', 'mukingosacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO MUYIRA DUSHYIGIKIRANE', 'MUYIRA', 'NYANZA', 'SOUTHERN PROVINCE', 'sacco.muyira@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE URUMURI RW''AMAJYAMBERE', 'NTYAZO', 'NYANZA', 'SOUTHERN PROVINCE', 'saccourumuri1@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO GANAHEZA NYAGISOZI', 'NYAGISOZI', 'NYANZA', 'SOUTHERN PROVINCE', 'sacconyagisozi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IGISUBIZO RWABICUMA', 'RWABICUMA', 'NYANZA', 'SOUTHERN PROVINCE', 'saccoigisubizorwabicuma@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC INGERI GISHAMVU', 'GISHAMVU', 'HUYE', 'SOUTHERN PROVINCE', 'gishamvusacco@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUJYANE HUYE SACCO', 'HUYE', 'HUYE', 'SOUTHERN PROVINCE', 'tuhusa@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TUGEREHEZA KARAMA', 'KARAMA', 'HUYE', 'SOUTHERN PROVINCE', 'karamasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TEGANYA KIGOMA SACCO', 'KIGOMA', 'HUYE', 'SOUTHERN PROVINCE', 'kigomasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KINAZI AMIZERO SACCO', 'KINAZI', 'HUYE', 'SOUTHERN PROVINCE', 'amizerosaccokinazi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC KIRA MARABA', 'MARABA', 'HUYE', 'SOUTHERN PROVINCE', 'saccomaraba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MBAZI ISONGA SACCO', 'MBAZI', 'HUYE', 'SOUTHERN PROVINCE', 'isongasaccombazi@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UBWUGAMO MUKURA SACCO', 'MUKURA', 'HUYE', 'SOUTHERN PROVINCE', 'mukurasacco2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ISANGE NGOMA SACCO', 'NGOMA', 'HUYE', 'SOUTHERN PROVINCE', 'ngomasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUGENDANE N''IGIHE RUHASHYA SACCO', 'RUHASHYA', 'HUYE', 'SOUTHERN PROVINCE', 'tugendanenigihe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SHISHOZA UKIRE RUSATIRA SACCO', 'RUSATIRA', 'HUYE', 'SOUTHERN PROVINCE', 'saccorusatira@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO HIRWA RWANIRO', 'RWANIRO', 'HUYE', 'SOUTHERN PROVINCE', 'saccorwaniro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('DUKIRE SIMBI SACCO', 'SIMBI', 'HUYE', 'SOUTHERN PROVINCE', 'simbisacco5@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RATWA TUMBA SACCO', 'TUMBA', 'HUYE', 'SOUTHERN PROVINCE', 'ratwasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TERIMBERE KIBIRIZI SACCO', 'KIBIRIZI', 'GISAGARA', 'SOUTHERN PROVINCE', 'termbere@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IZERE GIKONKO', 'GIKONKO', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccoizeregikonko@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC URUGERO MUGOMBWA', 'MUGOMBWA', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccourugeromugombwa@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('URUMURI MAMBA SACCO', 'MAMBA', 'GISAGARA', 'SOUTHERN PROVINCE', 'mambasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDATWA KIGEMBE', 'KIGEMBE', 'GISAGARA', 'SOUTHERN PROVINCE', 'indatwasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IMBEREHEZA NDORA', 'NDORA', 'GISAGARA', 'SOUTHERN PROVINCE', 'imberehezandora@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDASHYIKIRWA MUGANZA', 'MUGANZA', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccomuganza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INTWARI SACCO SAVE', 'SAVE', 'GISAGARA', 'SOUTHERN PROVINCE', 'intwarisaccosave@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO NYANZA DUKIRE', 'NYANZA', 'GISAGARA', 'SOUTHERN PROVINCE', 'nyanzadukire611@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TUGANEHEZA GISHUBI', 'GISHUBI', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccogishubi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUCYO SACCO MUKINDO', 'MUKINDO', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccomukindo@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ISHYAKA KANSI SACCO', 'KANSI', 'GISAGARA', 'SOUTHERN PROVINCE', 'saccoishyakakansi2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ITEGANYIRIZE MUSHA', 'MUSHA', 'GISAGARA', 'SOUTHERN PROVINCE', 'mushasacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KIRA BURUHUKIRO', 'BURUHUKIRO', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'saccokiraburuhukiro12@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBEREHEZA CYANIKA SACCO', 'CYANIKA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'cyanikasaccoimbereheza@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INGENZI GASAKA SACCO', 'GASAKA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'ingenzigasakasacco82@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO JYAMBERE GATARE', 'GATARE', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'gataresacco04@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('URUFUNGUZO RW''UBUKIRE KADUHA SACCO', 'KADUHA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'saccokaduha@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDAHIGWA KAMEGERI', 'KAMEGERI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'saccoindahigwakamegeri@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDATWA KIBIRIZI', 'KIBIRIZI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'indatwakibirizisacco16@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDANGAMIRWA KIBUMBWE SACCO (IKS)', 'KIBUMBWE', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'indangamirwakibumbwesacco2022@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TWITEGANYIRIZE KITABI', 'KITABI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'twiteganyirizekitabisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ICYEREKEZO MBAZI SACCO (IMS)', 'MBAZI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'icyerekezombazisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INSHUTI Z''I MUGANO SACCO', 'MUGANO', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'inshutizimuganosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('URUMURI RWA MUSANGE SACCO (UMS)', 'MUSANGE', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'musangesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDATWA MUSEBEYA', 'MUSEBEYA', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'indatwamusebeyasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDASHYIKIRWA MUSHUBI SACCO', 'MUSHUBI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'indashyikirwamushubisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUBWAMBUKENKOMANE SACCO', 'NKOMANE', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'tubwambukenkomanesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TUZAMURANE TARE', 'TARE', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'tuzamuranetaresacco2009@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IBYIRINGIRO UWINKINGI', 'UWINKINGI', 'NYAMAGABE', 'SOUTHERN PROVINCE', 'ibyiringirosacco.uwinkingi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO JYAMBERE BUSANZE', 'BUSANZE', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccojyamberebusanze@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO AMIZERO CYAHINDA', 'CYAHINDA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'cyahindasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IMBONI KIBEHO', 'KIBEHO', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccoimbonikibeho@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INKINGI Y''ITERAMBERE KIVU', 'KIVU', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccokivu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ITEZIMBERE MATA', 'MATA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccomata@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO UMURAVA MUGANZA', 'MUGANZA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccoumurava@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO WISIGARA MUNINI', 'MUNINI', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccowisigaramunini@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TWIZIGAMIRE NGERA', 'NGERA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccotwizigamire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ZAMUKA NGOMA', 'NGOMA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccozamuka@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UKURI NYABIMATA SACCO', 'NYABIMATA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'nyabimatasaccoukuri@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO EJOHAZAZA NYAGISOZI', 'NYAGISOZI', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccoejohazazanyagisozi70@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO NKUNGANIRE', 'RUHERU', 'NYARUGURU', 'SOUTHERN PROVINCE', 'nkunganiresaccco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KORUKIRE RURAMBA', 'RURAMBA', 'NYARUGURU', 'SOUTHERN PROVINCE', 'korukiresacco1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INOZAMIHIGO RUSENGE', 'RUSENGE', 'NYARUGURU', 'SOUTHERN PROVINCE', 'saccoinozamihigorusenge@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IZUBA SACCO BASE', 'BASE', 'RULINDO', 'NORTHERN PROVINCE', 'izubasacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBADUKO SACCO BUREGA', 'BUREGA', 'RULINDO', 'NORTHERN PROVINCE', 'imbadukosaccoburega@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPERATIVE DE DEVELOPMENT DE BUSHOKI', 'BUSHOKI', 'RULINDO', 'NORTHERN PROVINCE', 'coopedebusaccobushoki@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GIRUBUKIRE SACCO BUYOGA', 'BUYOGA', 'RULINDO', 'NORTHERN PROVINCE', 'girubukire@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IGISABO CYINZUZI SACCO', 'CYINZUZI', 'RULINDO', 'NORTHERN PROVINCE', 'cyinzuzisacco@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TERIMBERE SACCO CYUNGO', 'CYUNGO', 'RULINDO', 'NORTHERN PROVINCE', 'saccotecyu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVETUGIRUBUKIRE KINIHIRA', 'KINIHIRA', 'RULINDO', 'NORTHERN PROVINCE', 'kotukisacco@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUSINGIMW ITERAMBERE (UMITE)', 'KISARO', 'RULINDO', 'NORTHERN PROVINCE', 'saccoumite@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO COOPEBAMU', 'MASORO', 'RULINDO', 'NORTHERN PROVINCE', 'saccomasoro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MBOGO DEVELOPMENT COOPERATIVE', 'MBOGO', 'RULINDO', 'NORTHERN PROVINCE', 'mdecosaccombogo@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IJABO SACCO MURAMBI', 'MURAMBI', 'RULINDO', 'NORTHERN PROVINCE', 'saccoimu123@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SHIRUBUKENE SACCO NGOMA', 'NGOMA', 'RULINDO', 'NORTHERN PROVINCE', 'saccongoma@yahoo.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INGANZA SACCO NTARABANA', 'NTARABANA', 'RULINDO', 'NORTHERN PROVINCE', 'inganzasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPERATIVE GARAGAZUMUSARURO RUKOZO', 'RUKOZO', 'RULINDO', 'NORTHERN PROVINCE', 'saccorukozo2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBARUTSO SACCO RUSIGA', 'RUSIGA', 'RULINDO', 'NORTHERN PROVINCE', 'saccoimbarutso@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('BADUKA SACCO SHYORONGI', 'SHYORONGI', 'RULINDO', 'NORTHERN PROVINCE', 'badukashyorongisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ABAHIZI SACCO TUMBA', 'TUMBA', 'RULINDO', 'NORTHERN PROVINCE', 'saccoabahizitumba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO BUSENGO', 'BUSENGO', 'GAKENKE', 'NORTHERN PROVINCE', 'busengosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('REBAKURE SACCO', 'COKO', 'GAKENKE', 'NORTHERN PROVINCE', 'saccorebakurecoko@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('CYABINGO SACCO', 'CYABINGO', 'GAKENKE', 'NORTHERN PROVINCE', 'saccocyabingo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KUNGAHARA GAKENKE', 'GAKENKE', 'GAKENKE', 'NORTHERN PROVINCE', 'saccokungahara@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO GASE', 'GASHENYI', 'GAKENKE', 'NORTHERN PROVINCE', 'saccogase123@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UZAZUREBE SACCO', 'JANJA', 'GAKENKE', 'NORTHERN PROVINCE', 'saccojanja@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IZIYIGIHE SACCO', 'KAMUBUGA', 'GAKENKE', 'NORTHERN PROVINCE', 'iziyigihesacco18@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KARAMBO VA MU BUKENE SACCO', 'KARAMBO', 'GAKENKE', 'NORTHERN PROVINCE', 'kavabusacco7@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GIRINTEGO SACCO', 'KIVURUGA', 'GAKENKE', 'NORTHERN PROVINCE', 'girintegosacco2021@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SIGARABUKENE SACCO', 'MATABA', 'GAKENKE', 'NORTHERN PROVINCE', 'sigarabukenesaccomataba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO INDASHYIKIRWA', 'MINAZI', 'GAKENKE', 'NORTHERN PROVINCE', 'saccominazi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO NEW HOPE', 'MUGUNGA', 'GAKENKE', 'NORTHERN PROVINCE', 'sacconewhope@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TWAMBUTSANYE', 'MUHONDO', 'GAKENKE', 'NORTHERN PROVINCE', 'twambusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KATAZA MUYONGWE', 'MUYONGWE', 'GAKENKE', 'NORTHERN PROVINCE', 'muyongwesaccokataza2020@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('', 'MUZO', 'GAKENKE', 'NORTHERN PROVINCE', 'saccotugireubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDASHYIKIRWA SACCO', 'NEMBA', 'GAKENKE', 'NORTHERN PROVINCE', 'isacconemba@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBONERA SACCO', 'RULI', 'GAKENKE', 'NORTHERN PROVINCE', 'imboneraruli@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TUGIRE UBUKIRE', 'RUSASA', 'GAKENKE', 'NORTHERN PROVINCE', 'saccotugireubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUSINGI SACCO RUSHASHI', 'RUSHASHI', 'GAKENKE', 'NORTHERN PROVINCE', 'umusingisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ISONGA SACCO', 'BUNGWE', 'BURERA', 'NORTHERN PROVINCE', 'saccobungwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NDORWA SACCO', 'BUTARO', 'BURERA', 'NORTHERN PROVINCE', 'saccondorwabutaro@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IYUNGURE CYANIKA', 'CYANIKA', 'BURERA', 'NORTHERN PROVINCE', 'iyunguresacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURUNGA W''ITERAMBERE SACCO CYERU', 'CYERU', 'BURERA', 'NORTHERN PROVINCE', 'saccocyeru@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO AKABANDO', 'GAHUNGA', 'BURERA', 'NORTHERN PROVINCE', 'saccoakabando@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO DUKIRE GATEBE', 'GATEBE', 'BURERA', 'NORTHERN PROVINCE', 'saccodukiregatebee@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GITOVU SACCO', 'GITOVU', 'BURERA', 'NORTHERN PROVINCE', 'saccogitovu@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KAGOGO VISION SACCO (KAVISACCO)', 'KAGOGO', 'BURERA', 'NORTHERN PROVINCE', 'kavisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KINONI SACCO', 'KINONI', 'BURERA', 'NORTHERN PROVINCE', 'kinonisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDORERWAMO KINYABABA SACCO', 'KINYABABA', 'BURERA', 'NORTHERN PROVINCE', 'saccoindorerwamo2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPEC ICYEREKEZO KIZIMA', 'KIVUYE', 'BURERA', 'NORTHERN PROVINCE', 'saccoicyerekezokizima@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('DUHORANE IJABO SACCO', 'NEMBA', 'BURERA', 'NORTHERN PROVINCE', 'duhoraneijabo54@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO RUGARAMA IMBERE HEZA', 'RUGARAMA', 'BURERA', 'NORTHERN PROVINCE', 'saccorugarama@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURAGE SACCO', 'RUGENGABARI', 'BURERA', 'NORTHERN PROVINCE', 'umuragesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RUHUNDE SACCO', 'RUHUNDE', 'BURERA', 'NORTHERN PROVINCE', 'ruhundesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO REBAKURE RUSARABUYE', 'RUSARABUYE', 'BURERA', 'NORTHERN PROVINCE', 'saccorebakure@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('RUGEZI SACCO', 'RWERERE', 'BURERA', 'NORTHERN PROVINCE', 'saccorugezi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('BUKURE SACCO', 'BUKURE', 'GICUMBI', 'NORTHERN PROVINCE', 'bukuresacco2018@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBARUTSO SACCO', 'GITI', 'GICUMBI', 'NORTHERN PROVINCE', 'imbarutsosaccogiti@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMBONI SACCO KAGEYO', 'KAGEYO', 'GICUMBI', 'NORTHERN PROVINCE', 'imbonisacco@yahoo.fr', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('AGASHYA MANYAGIRO SACCO', 'MANYANGIRO', 'GICUMBI', 'NORTHERN PROVINCE', 'manyagirosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('WISIGARA RUSHAKI SACCO', 'RUSHAKI', 'GICUMBI', 'NORTHERN PROVINCE', 'wisigararushakisacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TSIMBURA SACCO', 'SHANGASHA', 'GICUMBI', 'NORTHERN PROVINCE', 'Saccotsimbura@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIRA MUTETE SACCO', 'MUTETE', 'GICUMBI', 'NORTHERN PROVINCE', 'kiramutete@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('HASHYUBUKENE SACCO RWAMIKO', 'RWAMIKO', 'GICUMBI', 'NORTHERN PROVINCE', 'saccorwamiko@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('BYUMBA SACCO', 'BYUMBA', 'GICUMBI', 'NORTHERN PROVINCE', 'byumbasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('BWISIGE SACCO', 'BWISIGE', 'GICUMBI', 'NORTHERN PROVINCE', 'bwisigesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUGENDANE N''IGIHE SACCO', 'KANIGA', 'GICUMBI', 'NORTHERN PROVINCE', 'stugendanenigihe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IBAKWE SACCO MUKARANGE', 'MUKARANGE', 'GICUMBI', 'NORTHERN PROVINCE', 'saccoibakwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURABYO SACCO NYAMIYAGA', 'NYAMIYAGA', 'GICUMBI', 'NORTHERN PROVINCE', 'umurabyosacconyamiyaga@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMIRASIRE Y''ITERAMBERE SACCO RUKOMO', 'RUKOMO', 'GICUMBI', 'NORTHERN PROVINCE', 'rukomosacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ITEGANYIRIZE SACCO RUTARE', 'RUTARE', 'GICUMBI', 'NORTHERN PROVINCE', 'saccorutare@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SHIRUBUKENE SACCO RUVUNE', 'RUVUNE', 'GICUMBI', 'NORTHERN PROVINCE', 'shirubukenescco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IZIGAMIRE SACCO MIYOVE', 'MIYOVE', 'GICUMBI', 'NORTHERN PROVINCE', 'isaccomiyove@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('TUVUDUKE SACCO RUBAYA', 'RUBAYA', 'GICUMBI', 'NORTHERN PROVINCE', 'tuvudukerubaya123@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('MFASHNKIRE SACCO', 'NYANKENKE', 'GICUMBI', 'NORTHERN PROVINCE', 'nyankenkesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INDATWA SACCO MUKO', 'MUKO', 'GICUMBI', 'NORTHERN PROVINCE', 'indatwasaccomuko1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('HIRWA CYUMBA SACCO', 'CYUMBA', 'GICUMBI', 'NORTHERN PROVINCE', 'hirwasacco10@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IHIRWE BUSOGO SACCO', 'BUSOGO', 'MUSANZE', 'NORTHERN PROVINCE', 'ihirwesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INYONGERA SACCO', 'CYUVE', 'MUSANZE', 'NORTHERN PROVINCE', 'saccoinyongera@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NEW VISION SACCO', 'GACACA', 'MUSANZE', 'NORTHERN PROVINCE', 'sacconewvisiongacaca@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURAVA SACCO GASHAKI', 'GASHAKI', 'MUSANZE', 'NORTHERN PROVINCE', 'umuravasaccogashaki@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('GATARAGA TWIBUMBE SACCO', 'GATARAGA', 'MUSANZE', 'NORTHERN PROVINCE', 'saccogataragatwibumbe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KIMONYI SACCO', 'KIMONYI', 'MUSANZE', 'NORTHERN PROVINCE', 'kimonyisacco506@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO ABIHUTA KINIGI', 'KINIGI', 'MUSANZE', 'NORTHERN PROVINCE', 'sakimanager@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ABAMUHOZA SACCO', 'MUHOZA', 'MUSANZE', 'NORTHERN PROVINCE', 'abamsacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO IRENGERE', 'MUKO', 'MUSANZE', 'NORTHERN PROVINCE', 'irengeresacco250@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUTUZO SACCO', 'MUSANZE', 'MUSANZE', 'NORTHERN PROVINCE', 'umutuzosacco2021@gmial.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IGIHONDOHONDOSACCO', 'NKOTSI', 'MUSANZE', 'NORTHERN PROVINCE', 'saccoigihondo@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('INYANGE SACCO', 'NYANGE', 'MUSANZE', 'NORTHERN PROVINCE', 'inyangesacco66@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ITEGANYIRIZE SACCO', 'REMERA', 'MUSANZE', 'NORTHERN PROVINCE', 'iteganyirizesacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMUSINGI RWAZA SACCO', 'RWAZA', 'MUSANZE', 'NORTHERN PROVINCE', 'saccoumusingi@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('NEZERWA 2020 SACCO', 'SHINGIRO', 'MUSANZE', 'NORTHERN PROVINCE', 'nezerwasacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO TWIHUTE KARAGO', 'KARAGO', 'NYABIHU', 'WESTERN PROVINCE', 'usaccokarago@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('KOPERATIVE IMBARUTSO Y''UBUKIRE', 'JOMBA', 'NYABIHU', 'WESTERN PROVINCE', 'imbarutsoyubukire@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IFUMBA Y''UBUKIRE', 'RAMBURA', 'NYABIHU', 'WESTERN PROVINCE', 'usaccorambura2@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('SACCO KIRA KABATWA', 'KABATWA', 'NYABIHU', 'WESTERN PROVINCE', 'saccokira1@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('IMIRASIRE SACCO', 'KINTOBO', 'NYABIHU', 'WESTERN PROVINCE', 'imirasirek@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('UMURAVA SACCO BIGOGWE', 'BIGOGWE', 'NYABIHU', 'WESTERN PROVINCE', 'saccobigogwe@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('ISOKO Y''AMAJYAMBERE SACCO', 'MUKAMIRA', 'NYABIHU', 'WESTERN PROVINCE', 'usaccomukamira@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE'),
('COOPERATIVE D''EPARGNE ET DE CREDIT DE RUGERA', 'RUGERA', 'NYABIHU', 'WESTERN PROVINCE', 'coecrusacco@gmail.com', 'Deposit-Taking Microfinance Cooperative (UMURENGE SACCO)', 'ACTIVE')
ON CONFLICT DO NOTHING;
